# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35ticsg324-1L

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/Digilent/programe/Digilent_contest/Digilent_contest.cache/wt [current_project]
set_property parent.project_path E:/Digilent/programe/Digilent_contest/Digilent_contest.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:arty:part0:1.1 [current_project]
set_property ip_repo_paths e:/Digilent/vivado-library [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files E:/Digilent/programe/Digilent_contest/Digilent_contest.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all e:/Digilent/programe/Digilent_contest/Digilent_contest.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/Digilent/programe/Digilent_contest/Digilent_contest.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/Digilent/programe/Digilent_contest/Digilent_contest.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Digilent/programe/Digilent_contest/Digilent_contest.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/Digilent/programe/Digilent_contest/Digilent_contest.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Digilent/programe/Digilent_contest/Digilent_contest.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/Digilent/programe/Digilent_contest/Digilent_contest.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_0/design_1_PmodMTDS_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/Digilent/programe/Digilent_contest/Digilent_contest.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_0/src/PmodMTDS_pmod_bridge_0_0/PmodMTDS_pmod_bridge_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/Digilent/programe/Digilent_contest/Digilent_contest.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_0/src/PmodMTDS_pmod_bridge_0_0/src/pmod_concat_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Digilent/programe/Digilent_contest/Digilent_contest.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_0/src/PmodMTDS_axi_quad_spi_0_0/PmodMTDS_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/Digilent/programe/Digilent_contest/Digilent_contest.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_0/src/PmodMTDS_axi_quad_spi_0_0/PmodMTDS_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/Digilent/programe/Digilent_contest/Digilent_contest.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_0/src/PmodMTDS_axi_quad_spi_0_0/PmodMTDS_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Digilent/programe/Digilent_contest/Digilent_contest.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_0/src/PmodMTDS_axi_quad_spi_0_0/PmodMTDS_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/Digilent/programe/Digilent_contest/Digilent_contest.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_0/src/axi_timer_0/axi_timer_0.xdc]
set_property used_in_implementation false [get_files -all e:/Digilent/programe/Digilent_contest/Digilent_contest.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_0/src/axi_timer_0/axi_timer_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Digilent/programe/Digilent_contest/Digilent_contest.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_0/src/PmodMTDS_axi_gpio_0_0/PmodMTDS_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/Digilent/programe/Digilent_contest/Digilent_contest.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_0/src/PmodMTDS_axi_gpio_0_0/PmodMTDS_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Digilent/programe/Digilent_contest/Digilent_contest.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_0/src/PmodMTDS_axi_gpio_0_0/PmodMTDS_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/Digilent/programe/Digilent_contest/Digilent_contest.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_0/src/PmodMTDS_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Digilent/programe/Digilent_contest/Digilent_contest.srcs/sources_1/bd/design_1/ip/design_1_PmodBT2_0_0/design_1_PmodBT2_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/Digilent/programe/Digilent_contest/Digilent_contest.srcs/sources_1/bd/design_1/ip/design_1_PmodBT2_0_0/src/PmodBT2_axi_uart16550_0_0/PmodBT2_axi_uart16550_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/Digilent/programe/Digilent_contest/Digilent_contest.srcs/sources_1/bd/design_1/ip/design_1_PmodBT2_0_0/src/PmodBT2_axi_uart16550_0_0/PmodBT2_axi_uart16550_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Digilent/programe/Digilent_contest/Digilent_contest.srcs/sources_1/bd/design_1/ip/design_1_PmodBT2_0_0/src/PmodBT2_axi_uart16550_0_0/PmodBT2_axi_uart16550_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/Digilent/programe/Digilent_contest/Digilent_contest.srcs/sources_1/bd/design_1/ip/design_1_PmodBT2_0_0/src/PmodBT2_axi_gpio_0_0/PmodBT2_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/Digilent/programe/Digilent_contest/Digilent_contest.srcs/sources_1/bd/design_1/ip/design_1_PmodBT2_0_0/src/PmodBT2_axi_gpio_0_0/PmodBT2_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Digilent/programe/Digilent_contest/Digilent_contest.srcs/sources_1/bd/design_1/ip/design_1_PmodBT2_0_0/src/PmodBT2_axi_gpio_0_0/PmodBT2_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/Digilent/programe/Digilent_contest/Digilent_contest.srcs/sources_1/bd/design_1/ip/design_1_PmodBT2_0_0/src/PmodBT2_pmod_bridge_0_0/PmodBT2_pmod_bridge_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/Digilent/programe/Digilent_contest/Digilent_contest.srcs/sources_1/bd/design_1/ip/design_1_PmodBT2_0_0/src/PmodBT2_pmod_bridge_0_0/src/pmod_concat_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Digilent/programe/Digilent_contest/Digilent_contest.srcs/sources_1/bd/design_1/ip/design_1_PmodBT2_0_0/src/PmodBT2_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Digilent/programe/Digilent_contest/Digilent_contest.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/Digilent/programe/Digilent_contest/Digilent_contest.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all e:/Digilent/programe/Digilent_contest/Digilent_contest.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Digilent/programe/Digilent_contest/Digilent_contest.srcs/sources_1/bd/design_1/ip/design_1_dlmb_v10_0/design_1_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all e:/Digilent/programe/Digilent_contest/Digilent_contest.srcs/sources_1/bd/design_1/ip/design_1_dlmb_v10_0/design_1_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Digilent/programe/Digilent_contest/Digilent_contest.srcs/sources_1/bd/design_1/ip/design_1_ilmb_v10_0/design_1_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all e:/Digilent/programe/Digilent_contest/Digilent_contest.srcs/sources_1/bd/design_1/ip/design_1_ilmb_v10_0/design_1_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Digilent/programe/Digilent_contest/Digilent_contest.srcs/sources_1/bd/design_1/ip/design_1_dlmb_bram_if_cntlr_0/design_1_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Digilent/programe/Digilent_contest/Digilent_contest.srcs/sources_1/bd/design_1/ip/design_1_ilmb_bram_if_cntlr_0/design_1_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Digilent/programe/Digilent_contest/Digilent_contest.srcs/sources_1/bd/design_1/ip/design_1_lmb_bram_0/design_1_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Digilent/programe/Digilent_contest/Digilent_contest.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all e:/Digilent/programe/Digilent_contest/Digilent_contest.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all e:/Digilent/programe/Digilent_contest/Digilent_contest.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_0_100M_0/design_1_rst_clk_wiz_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/Digilent/programe/Digilent_contest/Digilent_contest.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_0_100M_0/design_1_rst_clk_wiz_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all e:/Digilent/programe/Digilent_contest/Digilent_contest.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_0_100M_0/design_1_rst_clk_wiz_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Digilent/programe/Digilent_contest/Digilent_contest.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all E:/Digilent/programe/Digilent_contest/Digilent_contest.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property is_locked true [get_files E:/Digilent/programe/Digilent_contest/Digilent_contest.srcs/sources_1/bd/design_1/design_1.bd]

read_verilog -library xil_defaultlib E:/Digilent/programe/Digilent_contest/Digilent_contest.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top design_1_wrapper -part xc7a35ticsg324-1L
write_checkpoint -noxdef design_1_wrapper.dcp
catch { report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb }
